# Generated by Django 3.0.6 on 2020-05-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID', '0002_auto_20200523_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
