# Generated by Django 3.0.6 on 2020-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID', '0003_auto_20200523_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact', models.CharField(max_length=500)),
            ],
        ),
    ]
